#!/bin/ksh
set -e
cd ../build
rm -f src/suidsh
make
sudo chown root:wheel src/suidsh
sudo chmod 4555 src/suidsh
cd ../test
set +e
./testme arg1 arg2 arg3
echo "------------------------------------------------------------"
PATH=`pwd`:$PATH
export PATH
testme arg1 arg2 arg3
